Vagrant.configure("2") do |config|
    config.vm.box = "debian/bullseye64"
    config.vm.provider "virtualbox" do |v|
        v.gui = false
        v.name = "openvpn_lab"
        v.cpus = 2
        v.memory = 1024
    end
    config.vm.network "public_network", use_dhcp_assigned_default_route: true
end
